{{- if .Values.api.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "api.fullname" . }}
  labels:
    app: {{ template "api.fullname" . }}
    chart: {{ template "chart" . }}
    draft: {{ .Values.draft | default "draft-app" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.api.ingress.annotations }}
  annotations:    
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
  - host: {{ .Values.api.ingress.hostname }}
    http:
      paths:
      - path: {{ .Values.api.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ template "api.fullname" . }}
            port: 
              name: http
{{- end }}
