apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "api.fullname" . }}
  labels:
    app: {{ template "api.fullname" . }}
spec:
  rules:
  - host: {{ .Values.api.ingress.hostname }}
    http:
      paths:
      - path: {{ .Values.api.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ template "api.fullname" . }}
            port: 
              name: http
