apiVersion: v1
kind: Service
metadata:
  name: {{ template "api.fullname" . }}
  labels:
    app: {{ template "api.fullname" . }}
    chart: {{ template "chart" . }}
    draft: {{ .Values.draft | default "draft-app" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "api.fullname" . }}
    release: {{ .Release.Name }}
