fullnameOverride: calculator

api:
  subName: api
  replicaCount: 1

  image:
    name: registry.minikube/calculator-api:latest
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 30001

  ingress:
    path: /
    hostname: calculator-api.kubernetes-examples.test

application:
  environment: Development
  logging:
    level: Debug
  