fullnameOverride: calculator

api:
  subName: api
  replicaCount: 1

  image:
    name: docker.io/andrejfurtak/calculator-api:latest
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 30001

  ingress:
    enabled: false
    annotations: {}
    path: /
    hostname: calculator-api.kubernetes-examples.test

application:
  environment: Development
  logLevels: 
    default: warning
  