fullnameOverride: calculator

api:
  subName: api
  replicaCount: 1

  image:
    name: calculator-api
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 30001

  ingress:
    enabled: false
    annotations: {}
    path: /
    hostname: calculator-api


application:
  environment: Development
  logLevels: 
    default: warning
  