apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: calculator

build:

  artifacts:

  - image: calculator-api
    context: ..
    docker:
      dockerfile: ./Calculator.Api/Dockerfile
      
  tagPolicy:
    sha256: {}

  local:
    push: true
    useDockerCLI: true
    useBuildkit: true

deploy:

  helm:

    releases:

    - name: calculator
      chartPath: ./charts/calculator
      wait: true
      artifactOverrides:
        api.image.name: calculator-api

profiles:
    
- name: local
  patches:

  - op: add
    path: /deploy/helm/releases/0/valuesFiles
    value:
      - values.local.yaml
